server:
  port: 8080 
  servlet:
    context-path: /
spring:
  application:
    name: alinsno-lin-demo
  datasource:
    url: jdbc:mysql://db4free.net:3306/thoseyears?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=GMT
    username: thoseyears
    password: 110120lin..
  redis:
    host: 127.0.0.1
    port: 6379   
    password: 
  devtools:
    restart:
      enabled: false 
   
dubbo:
  application:
    name: alinsno-lin-demo
  config-center:
    address: zookeeper://127.0.0.1:2181
  metadata-report:
    address: zookeeper://127.0.0.1:2181
  registry:
    address: zookeeper://127.0.0.1:2181
